'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Protected Overrides Sub OnCreateMainForm()
            Try
                EarlyLog.WriteStartupBreadcrumb()
                Me.MainForm = Global.runInstallScript.Installing
            Catch ex As Exception
                EarlyLog.WriteException("OnCreateMainForm", ex)
                Throw
            End Try
        End Sub

        Protected Overrides Function OnUnhandledException(ByVal e As Global.Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs) As Boolean
            EarlyLog.WriteException("UnhandledException", e.Exception)
            Return MyBase.OnUnhandledException(e)
        End Function
    End Class
End Namespace
